libnav/urls.py
from django.urls import path
from libnav import views

app_name = 'libnav'

urlpatterns = [
    path('', views.home, name='home'),
    path('map/<floor_number>/', views.map, name='map'),
    path('about/', views.about, name= 'about'),
    path('profile/<username>/', views.profile, name = 'profile'),
    path('book/<isbn>/', views.book, name ='book'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('api/set-loc/',views.api_set_loc,name="setloc"),
    path('api/get-loc/',views.api_get_loc,name="getloc"),
    path('api/remove-loc/', views.api_remove_loc, name="removeloc"),
    path('put/', views.put, name='put'),
    path('send_friend_request/<username>/', views.send_friend_request, name = 'send friend request'),
    path('accept_friend_request/<int:requestID>/', views.accept_friend_request, name = 'accept friend request'),
    path('delete_friend_request/<int:requestID>/', views.delete_friend_request, name = 'delete friend request'),
    path('edit_profile/', views.edit_profile, name = 'edit profile'),
    path('search/', views.search, name = 'search'),
    path('delete_friend/<username>/', views.delete_friend, name = 'delete friend'),
    path('book/<isbn>/update_book/', views.update_book, name = 'update_book'),
]

library_navigator/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from libnav import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('libnav/', include('libnav.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "library_navigator.views.page_not_found_view"

libnav/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Subject(models.Model):
    id = models.AutoField(primary_key=True , unique=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Floor(models.Model):
    number = models.IntegerField(primary_key=True)
    mapName = models.CharField( max_length= 20)
    def __str__(self):
        return "Floor "+ str(self.number)

class Bookcase(models.Model):
    id = models.CharField(max_length=10, primary_key=True, unique=True)
    floor = models.ForeignKey(Floor, on_delete=models.PROTECT)

    def __str__(self):
        return  str(self.id) +" on "+str(self.floor)


class Book(models.Model):
    ISBN = models.CharField(max_length=13, primary_key=True, unique=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    coverImage = models.ImageField(upload_to='book_cover_images',null=True)
    checkedOut = models.BooleanField(default=False)
    numCheckedOut = models.IntegerField(default=0)
    publishDate = models.DateField()
    numberOfPage = models.IntegerField()
    description = models.CharField(max_length=1000)
    likes = models.IntegerField(default=0)
    bookcase = models.ForeignKey(Bookcase, on_delete=models.PROTECT)
    subjects = models.ManyToManyField(Subject,related_name='book_subjects',blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to="profile_images",blank=True,default="profile_images/NONE.jpg")
    website = models.URLField(blank= True)
    description = models.CharField(max_length = 1000, blank=True)
    isReading = models.ManyToManyField(Book,related_name="user_isReading",blank=True)
    recommends = models.ManyToManyField(Book,related_name="user_recommends",blank=True)
    likes = models.ManyToManyField(Book,related_name="user_likes",blank=True)
    friends = models.ManyToManyField(User,related_name='user_friends',blank=True)
    favouriteFloor = models.ForeignKey(Floor, default=1, on_delete=models.PROTECT)
    def __str__(self):
        return self.user.username

class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name= 'from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)

libnav/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput, EmailInput, URLInput, FileInput, Textarea, Select
from libnav.models import User, UserProfile


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:

        model = User
        fields = ('username', 'email', 'password')
        widgets = {'username': TextInput(attrs={
            'type': 'text',
            'class': 'input',
            'id': 'id_username',
            'placeholder': ' ',
            }),
            'email': EmailInput(attrs={
            'type': 'email',
            'class': 'input',
            'id': 'id_email',
            'placeholder': ' ',
            }),
            'password': PasswordInput(attrs={
            'type': 'password',
            'class': 'input',
            'id': 'id_password',
            'placeholder': ' ',
            })}



class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('picture','website', 'description', 'favouriteFloor',)
        widgets = {
            'picture': FileInput(attrs={
            'type': 'file',
            'class': 'file-input',
            'id': 'id_picture',
            'accept': 'image/*',
            }),
            'website': URLInput(attrs={
            'type': 'url',
            'class': 'input',
            'id': 'id_email',
            'placeholder': ' ',
            }),
            'description': Textarea(attrs={
            'type': 'text',
            'class': 'input textarea',
            'id': 'id_password',
            'placeholder': ' ',
            }),
            'favouriteFloor': Select(attrs={
                'type': 'select',
                'class': 'input',
                'id':'id_floor',
                'placeholder':' ',
            })
            }

libnav/views.py
import json
from multiprocessing import context
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from libnav.models import Book, Bookcase, Floor, Subject, UserProfile, FriendRequest
from libnav.forms import UserForm, UserProfileForm
from django.shortcuts import redirect
from library_navigator.settings import MEDIA_URL
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from libnav.miscs.locations_keeper import locations,location

from django.http.response import JsonResponse


def put(request):
    if request.method == 'GET':
        return JsonResponse({"key": "value"})
    else:
        return HttpResponse()
        
def update_book(request, isbn):
    if request.method == 'GET':
        try:
            book = Book.objects.get(ISBN=isbn)
            value = int(request.GET.get('value'))
            action = request.GET.get('action')
        except (Book.DoesNotExist, ValueError, TypeError):
            return redirect(reverse('libnav:home'))
            
        # check if the request has been made by clicking the button
        if not request.META.get("HTTP_REFERER", '').endswith(reverse('libnav:book', kwargs={'isbn': isbn})):
            return redirect(reverse('libnav:home'))
        
        profile = UserProfile.objects.get(user = request.user)
        if action=='checkout':
            if value>0:
                profile.isReading.add(book)
                book.checkedOut = True 
                book.numCheckedOut = book.numCheckedOut + 1
            else:
                profile.isReading.remove(book)
                book.checkedOut = False 
            book.save()
            profile.save()
        if action=='like':
            book.likes = book.likes + value
            book.save()
            if value>0:
                profile.likes.add(book)
            else:
                profile.likes.remove(book)
            profile.save()
        if action=='recommend':
            if value>0:
                profile.recommends.add(book)
            else:
                profile.recommends.remove(book)
            profile.save()
            
        response = JsonResponse({"likes": book.likes})
        return response
    else:
        return redirect(reverse('libnav:home'))


def home(request):
    like_list = Book.objects.order_by('-likes')[:4]
    popular_list = Book.objects.order_by('-numCheckedOut')[:4]

    context_dict = {
        'liked': like_list,
        'popular': popular_list
    }
    response = render(request, 'libnav/home.html', context= context_dict)

    return response
def about(request):
    response = render(request, 'libnav/about.html')
    return response

def profile(request, username):
    context_dict = {}
    current_user = request.user
    context_dict["auth"] = None

    try:
        user = User.objects.get(username = username)
        userProfile = UserProfile.objects.get(user = user)
        context_dict["user"]= user
        context_dict["userProfile"] = userProfile
        recommended = userProfile.recommends.all()
        context_dict["recommended"] = recommended
        reading = userProfile.isReading.all()
        context_dict["reading"] = reading
        
    except User.DoesNotExist:
        context_dict["user"]= None
        context_dict["userProfile"] = None
        context_dict["recommended"] = None
        context_dict["reading"] = None


    else:
        if current_user.is_authenticated and user == current_user:
            return my_profile(request, username, context_dict= context_dict)

        if current_user.is_authenticated:
            context_dict["auth"] = True
            if userProfile.friends.filter(username = current_user).exists():
                context_dict['notFriends'] = False
            else:
                context_dict['notFriends'] = True

    return render(request, 'libnav/profile.html', context= context_dict)

def my_profile(request, username, context_dict):
    user = User.objects.get(username = username)
    userProfile = UserProfile.objects.get(user = user)
    
    try:
        context_dict["friends"] = userProfile.friends.all()
        context_dict["requests"] = FriendRequest.objects.filter(to_user = user)
    except:
        context_dict["friends"] = None
        context_dict['requests'] = None
    return render(request, 'libnav/my_profile.html', context= context_dict)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        current_user = request.user
        profile = UserProfile.objects.get(user = current_user)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            print(profile_form.cleaned_data)
            data = profile_form.cleaned_data
            if data['website']:
                profile.website = data['website']
            if data['description']:
                profile.description = data['description']
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            if data['favouriteFloor']:
                profile.favouriteFloor = data['favouriteFloor']
            profile.save()
            return redirect(reverse('libnav:profile', kwargs={'username': current_user.username}))
        else:
            print(profile_form.errors)
    else:
        context_dict = {'profile_form': UserProfileForm()}
        return render(request, 'libnav/edit_profile.html', context=context_dict)


def map(request, floor_number):
    context_dict ={}
    try:
        floor = Floor.objects.get(number = floor_number)
        context_dict['floor'] = floor
        books = Book.objects.filter(bookcase__in=Bookcase.objects.filter(floor=Floor.objects.get(number=floor_number))).order_by('-likes')
        context_dict['books'] = books
        context_dict['user'] = request.user.id
        busyness = min(locations.get_busyness_of_floor(int(floor_number)) // 5, 5)
        busyness_list = list(range(busyness))
        unbusyness_list = list(range(5 - busyness))
        context_dict['busyness'] = busyness_list
        context_dict['unbusyness'] = unbusyness_list
    except (Floor.DoesNotExist, Bookcase.DoesNotExist, ValueError):
        context_dict['floor'] = None
        context_dict['books'] = None
    response = render(request, 'libnav/map.html', context = context_dict)
    return response


def book(request, isbn):
    context_dict ={}
    try:
        book = Book.objects.get(ISBN = isbn)
        location = Bookcase.objects.get(id = book.bookcase.id)
        context_dict['book'] = book
        context_dict['bookcase'] = location
        context_dict['checked_out'] = book.checkedOut
        
        if request.user.is_authenticated:
            userprofile = request.user.userprofile
            # keys indicate whether specified button should be displayed
            # otherwise display the button that reverses the action
            context_dict['flags'] = {
                'checkout': userprofile.isReading.filter(ISBN=isbn).exists(), 
                'like': userprofile.likes.filter(ISBN=isbn).exists(), 
                'recommend': userprofile.recommends.filter(ISBN=isbn).exists(),}
    except Book.DoesNotExist:
        context_dict['book'] = None
    response = render(request, 'libnav/book.html', context=context_dict)
    return response

def user_login(request):
    if request.user.is_authenticated:
        return redirect(reverse('libnav:profile', kwargs={'username': request.user.username}))


    if request.method == 'POST':
        # login form
        login_form = ""

        if request.POST.get('submit') == 'Login':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username= username, password = password)

            if user:
                login(request, user)
                request.session['user_id'] = user.userprofile.user_id
                return redirect(reverse('libnav:home'))
            elif User.objects.filter(username=username).exists() and not User.objects.get(username=username).is_active:
                return HttpResponse("Your LIBNAV account is disabled.")
            else:
                login_form = "Invalid login details supplied."
                user_form = UserForm()

        # register form
        elif request.POST.get('submit') == 'Register':
            user_form = UserForm(request.POST)

            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                profile = UserProfile.objects.get_or_create(user = user)[0]
                profile.save()
                login(request, user)
                request.session['user_id'] = profile.user_id
                return redirect(reverse('libnav:profile', kwargs={'username': user.username}))
            else:
                print(user_form.errors)
    # not post
    else:
        login_form = ""
        user_form = UserForm()

    return render(request,
        'libnav/login.html',
        context = {
            'user_form': user_form,
            'login_form': login_form})

@login_required
def user_logout(request):
    logout(request)
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return redirect(reverse('libnav:home'))


def api_get_loc(request):
    user = request.GET.get('userID', None)
    floor = request.GET.get('floor', None)
    user_loc = []
    friends_loc = []
    public_loc = []
    if floor is not None:
        floor = int(floor)
    if user is not None and user != "null" and floor is not None:
        user = User.objects.get(id=user)
        userProfile = UserProfile.objects.get(user=user)

        a = list()

templates/libnav/about.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <div id="about">
        <h2><a href="https://github.com/lab9teamA/library-navigator/">WAD group project</a></h2>
        <ul>
            <li>The main purpose of our web app is to provide students and staff with an easy to use tool that allows them to set their location in the library, which can be visible to everyone, or just their friends.</li>

            <li>Users can view the layout and facilities provided on each floor of the library with official floor plans.</li>

            <li>Users have their own profile and can add their friends.</li>

            <li>Users can view books available in the library and their exact location(floor and shelf) as well as check them out, like them and recommend them to their friends.</li>
        </ul>
    </div>
{% endblock %}

templates/libnav/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load libnav_template_tags %}
{% get_user as current_user %}

<html>
    <head>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <title>
            LibNav -
            {% block title_block %}
                Home
            {% endblock %}
        </title>
    </head>
<body>
    <div class="wrapper">
        <div id="navbar">
            <ul>
                <li>
                    <form action="{% url 'libnav:search' %}" method="get">
                        <input id="search" name="search" placeholder="Search..." type="text">
                    </form>
                </li>
                <li><a href="{% url 'libnav:home' %}">Home</a></li>
                <li><a href="{% url 'libnav:map' 1 %}">Map</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{% url 'libnav:profile' current_user.username %}">My profile</a></li>
                <li><a href="{% url 'libnav:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'libnav:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
        <div id="bodyBlock">
            {% block body_block %}

            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
{#                {% get_floor_list floor %}#}
            {% endblock %}
        </div>
        <div class="footer">
            <ul>
                <li><a href="{% url 'libnav:about' %}">About</a></li>
            </ul>
        </div>
    </div>
</body>
</html>

templates/libnav/book.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}
{% load libnav_template_tags %}

{% block title_block %}
{% if book %}
{{ book.title }}
{% else %}
Unknown Book
{% endif %}
{% endblock %}

{% block body_block %}


<script src="{% static 'javascript/bookPageButtons.js' %}"></script>
<script type="text/javascript">
	var flags = {{ flags | set_variables }};
</script>

<div id="bookProfile">
    {% if book %}
    <div id="pageWrapper">
        <div id="bBook">
            <div class="content">
                {% if book.coverImage %}
                <img src="{{MEDIA_URL}}{{book.coverImage}}" alt="{{book.title}}">
                {%else%}
                <img src="https://image.shutterstock.com/image-vector/open-book-vector-clipart-silhouette-260nw-358417976.jpg">
                {%endif%}
                <h4><p id="likes">{{ book.likes }} like this</p></h4>
				{% if user.is_authenticated %}
                <ul>
					{% if checked_out and not flags.checkout %}
						<li>Currently not available for checkout</li>
					{% else %}
						<li id="checkoutButton"><button onclick="updateBook('checkout', 1)">Check Out</button></li>
						<li id="checkinButton" hidden><button onclick="updateBook('checkout', -1)">Check In</button></li>
					{% endif %}
                    <li id="likeButton"><button onclick="updateBook('like', 1)">Like</button></li>
					<li id="unlikeButton" hidden><button onclick="updateBook('like', -1)">Remove Like</button></li>
                    <li id="recommendButton"><button onclick="updateBook('recommend', 1)">Recommend</button></li>
					<li id="unrecommendButton" hidden><button onclick="updateBook('recommend', -1)">Remove Recommendation</button></li>
                </ul>
				{% endif %}
            </div>
        </div>
        <div id="infoBlock">
            <h2>{{ book.title }}</h2>
            <p>{{book.author}}</p>
            <div class="box" id="book">
                <p>{{book.description}}</p>
            </div>
            <div class="box" id="location">
                <p>published {{book.publishDate}}</p>
                <p>this book can be found at bookcase {{bookcase.id}} on <a
                        href="{% url 'libnav:map' bookcase.floor.number %}">floor {{bookcase.floor.number}}</a></p>

            </div>
        </div>
    </div>
    {% else %}
    Unknown Book
    {% endif %}

</div>

{% endblock %}

templates/libnav/edit_profile.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Edit Profile
{% endblock %}

{% block body_block %}
<div id="editPage">

    <div class="lrBlock">
        <form id="profile_form" method="post" action="{% url 'libnav:edit profile' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <h1>{{user.username}} - Edit Profile</h1>
            <div class="input-container" >
                <label for="id_picture">Picture</label>
                {{ profile_form.picture }}
            </div>

            <div class="input-container" id="pic">
                {{ profile_form.website }}
                <div class="cut"></div>
                <label class="placeholder" for="id_website">Website</label>
            </div>

            <div class="input-container">
                {{ profile_form.description }}
                <div class="cut"></div>
                <label class="placeholder" for="id_description">Description</label>
            </div>

            <div class="input-container">
                {{ profile_form.favouriteFloor }}
                <div class="cut" id="floorSelector"></div>
                <label class="placeholder" for="id_description">Favourite Floor</label>
            </div>

            <div class="submit-container">
                <input class="submit" name="submit" type="submit" value="save"/>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/libnav/home.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
<div id="mainHome">
    <div id="header">
        <br />
        <h1>Welcome to the home page of library navigator</h1>
    </div>
    <div class="header">
        <h3>Popular books in the library</h3>
    </div>
    {%if popular %}
    <div class="mPanel">
        <div id="pBooksBlock" class="selection">
            <div class="bookWrapper">
                {% for book in popular %}
                <div class="gallery">
                    <a href="{% url 'libnav:book' book.ISBN %}">
                        <img class="displayImage" src="{{MEDIA_URL}}{{book.coverImage}}" alt="{{book.title}}">
                        <div class="desc">
                            <div class="text">{{book.title}}</div>
                        </div>
                    </a>
                </div>
                {%endfor%}

            </div>
        </div>
    </div>
    {%endif%}
    <br />
    <div class="header">
        <h3>People like reading</h3>
    </div>
    <div class="mPanel">
        <div id="pReadingBlock" class="selection">
            <div class="bookWrapper">
                {%if liked%}
                {%for book in liked%}
                    <div class="gallery">
                        <a href="{% url 'libnav:book' book.ISBN %}">
                            <img class="displayImage" src="{{MEDIA_URL}}{{book.coverImage}}" alt="{{ book.title }}">
                            <div class="desc">
                                <div class="text">{{ book.title }}</div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
                {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/libnav/login.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login or Register
{% endblock %}

{% block body_block %}
<div id="loginPage">
    <div class="lrBlock" id="loginBlock">
        <div id="loginWrapper" class="lrWrapper">
            <h1>Login to library navigator</h1>
            <form action="{% url 'libnav:login' %}" id="login_form" method="post">
                {% csrf_token %}
                <div class="input-container ic1">
                    <input class="input" id="username" name="username" placeholder=" " type="text"/>
                    <div class="cut"></div>
                    <label class="placeholder" for="username">Username</label>
                </div>
                <div class="input-container ic2">
                    <input class="input" id="password" name="password" placeholder=" " type="password"/>
                    <div class="cut"></div>
                    <label class="placeholder" for="password">Password</label>
                </div>
                <div class="submit-container">
                    <input class="submit" name="submit" type="submit" value="Login"/>
                </div>
                {{login_form}}
            </form>
        </div>
    </div>

    <div class="lrBlock" id="registerBlock">
        <div id="registerWrapper" class="lrWrapper">
            <h1>Register a new account</h1>
            <form action="{% url 'libnav:login' %}" enctype="multipart/form-data" id="register_form" method="post">
                {% csrf_token %}

                <div class="input-container">
                    {{ user_form.username }}
                    <div class="cut"></div>
                    <label class="placeholder" for="id_username">Username</label>
                </div>

                <div class="input-container">
                    {{ user_form.email }}
                    <div class="cut"></div>
                    <label class="placeholder" for="id_email">Email</label>
                </div>

                <div class="input-container">
                    <input class="input" id="id_password" name="password" placeholder=" " type="password">
                    <div class="cut"></div>
                    <label class="placeholder" for="id_password">Password</label>
                </div>

                <div class="submit-container">
                    <input class="submit" name="submit" type="submit" value="Register"/>
                </div>

                {% if user_form.errors %}
                <ul class="errorList">
                    {% for key, value in user_form.errors.items reversed %}
                    <li>
                        {% if key == "password"%}
                            Password was not a valid entry.
                        {%elif key == "username"%}
                            Username is already taken.
                        {%else%}
                            Email is invalid.
                        {%endif%}
                    </li>
                    {%endfor%}
                </ul>
                {%endif%}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/libnav/map.html
{% extends 'libnav/base.html' %}
{% load staticfiles %}
{% load libnav_template_tags %}

{% block title_block %}
{% if floor %}
    Floor {{floor.number}}
{%else%}
    the floor you are trying to find does not exist.
{% endif %}
{% endblock %}

{% block body_block %}
    {{ user|json_script:"user-id" }}
	{{ floor.number|json_script:"floor_number" }}
    {{ floor.mapName|json_script:"floor_map" }}
    {{ MEDIA_URL|json_script:"media_url" }}
{% if floor %}
<div class="main">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static "javascript/Markers.js" %}"></script>
    <div class="child" id="mainbody">
        <div class="mainWrapper">
            <div id="scrollBar">
                <ul id="floorList">
                    {% for i in 12|floor_range %}
                        {% if i == floor.number%}
                            {%if i != 12%}
                                <li><a href="{% url 'libnav:map' floor.number|add:"1"  %}" class="arrow" id="arrow-up"></a></li>
                            {%endif%}

                            <li><a href="{% url 'libnav:map' i  %}">{{i}}</a></li>

                            {% if i != 1%}
                                <li><a href="{% url 'libnav:map' floor.number|add:"-1" %}" class="arrow" id="arrow-down"></a></li>
                            {%endif%}

                        {%else%}
                            <li><a href="{% url 'libnav:map' i  %}">{{i}}</a></li>
                        {%endif%}
                    {% endfor %}
                </ul>
            </div>
            <div id="imageLoc">
                <canvas id="canvas"></canvas>
            </div>
        </div>
    </div>
    <div class="child" id="sidebar">
    <div id="busyness">
        <h5>Busyness</h5>
        {% for x in busyness %}
            <span class="dot-on"></span>
        {% endfor %}
        {% for x in unbusyness %}
            <span class="dot"></span>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
    <div class="sWig">
        <h4>Friends on this level</h4>
        <div id="cFriendsInd">
			{% show_friends request.user floor.number %}
        </div>
    </div>
    {%endif%}
    <div class="sWig">
        <h4>Popular books on this level</h4>
        <div id="pBooksBlock">
        {% if books %}
        {%for book in books%}
            <li>
                <a href="{% url 'libnav:book' book.ISBN %}">{{ book.title }}</a>
            </li>
        {%endfor%}
        {% else %}
            There are no books on this floor
        {% endif %}
        </div>
    </div>
    </div>

    {%else%}
    <h1>
        the floor you are trying to find does not exist.
        <a href="{% url 'libnav:map' 1 %}">go to floor 1</a>
    </h1>
    {% endif %}
</div>
{% endblock %}